---

vars:
  name: apache
  servercode: php
  
steps:
  - plugin: aptget
    config:
       package: 
          - apache2
          - php
          - libapache2-mod-php
       state: install
       
  - plugin: filecopy
    config:
       name: index.php
       destination: /var/www/html
       
  - plugin: filecopy
    config:
       name: 000-default.conf
       destination: /etc/apache2/sites-available
           
  - plugin: service
    config:
       service: apache2
       action: restart
       
   